In [2]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [4]:
percentage = 100 * A / cal.reshape(1, 4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [5]:
a = np.random.randn(5)
print(a, a.T, np.dot(a, a.T), '\n')
a = np.random.randn(5, 1)
print(a, a.T, np.dot(a, a.T))

[-1.61360033 -0.4387201  -0.24587095  0.725348    0.79096069] [-1.61360033 -0.4387201  -0.24587095  0.725348    0.79096069] 4.008382404738041 

[[ 0.94901415]
 [-1.52867215]
 [ 0.86350372]
 [ 0.90019167]
 [-0.60509709]] [[ 0.94901415 -1.52867215  0.86350372  0.90019167 -0.60509709]] [[ 0.90062785 -1.4507315   0.81947725  0.85429463 -0.5742457 ]
 [-1.4507315   2.33683853 -1.32001409 -1.37609794  0.92499506]
 [ 0.81947725 -1.32001409  0.74563868  0.77731886 -0.52250358]
 [ 0.85429463 -1.37609794  0.77731886  0.81034505 -0.54470336]
 [-0.5742457   0.92499506 -0.52250358 -0.54470336  0.36614248]]
